DROP TABLE ABANDONEDDOG
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ABANDONEDDOG;

CREATE TABLE ABANDONEDDOG
(
SEQ NUMBER NOT NULL,                --시퀀스
MYID VARCHAR2(50) NOT NULL,         --아이디(FK)
PHONENUM NUMBER NOT NULL,           --연락처
ADDRESS VARCHAR2(200) NOT NULL,        --주소
MYCONTENT VARCHAR2(500),            --내용
FILENAME VARCHAR2(50) PRIMARY KEY, --동물이미지
NEWFILENAME VARCHAR2(50) NOT NULL, --이미지
DANGER NUMBER NOT NULL,                --위험 정도(1-3)
WDATE DATE NOT NULL                 --등록일
);

--외래키 연결 
ALTER TABLE ABANDONEDDOG
ADD
CONSTRAINT FK_INPET_ID FOREIGN KEY(MYID)
REFERENCES MYMEMBER(MYID);

CREATE SEQUENCE SEQ_ABANDONEDDOG
START WITH 1
INCREMENT BY 1; 

